# Generated by Django 5.1.7 on 2025-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='imageNo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
