# Generated by Django 5.1.6 on 2025-04-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0004_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='county',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
