# Generated by Django 5.1.7 on 2025-04-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0005_additional_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='bimages',
            name='siteName',
            field=models.CharField(default='The Berry Site', max_length=255),
        ),
    ]
