# Generated by Django 5.1.6 on 2025-04-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0006_annotations_z'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='z',
        ),
    ]
