# Generated by Django 5.1.7 on 2025-04-15 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0007_remove_annotations_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='siteName',
            field=models.CharField(default='The Berry Site', max_length=255),
        ),
        migrations.AddField(
            model_name='bimages',
            name='siteName',
            field=models.CharField(default='The Berry Site', max_length=255),
        ),
    ]
