# Generated by Django 5.1.6 on 2025-04-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0008_annotations_sitename_bimages_sitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='popupImage',
            field=models.ImageField(blank=True, null=True, upload_to='annotation_images/'),
        ),
    ]
