# Generated by Django 5.1.6 on 2025-04-22 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0009_annotations_popupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='popupText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
