# Generated by Django 5.1.6 on 2025-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0010_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='popupImage',
            field=models.ImageField(blank=True, null=True, upload_to='annotation_images/'),
        ),
        migrations.AddField(
            model_name='annotations',
            name='popupText',
            field=models.TextField(blank=True, null=True),
        ),
    ]
