# Generated by Django 5.2 on 2025-04-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0011_annotations_popupimage_annotations_popuptext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('imageNo', models.IntegerField()),
                ('siteName', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='stamps/')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
