# Generated by Django 5.1.6 on 2025-04-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0012_annotations_artifact_annotations_artifactimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='annotations',
            name='artifactImg',
        ),
    ]
