# Generated by Django 5.2 on 2025-04-29 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0013_annotations_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artifacts/')),
                ('siteName', models.CharField(default='The Berry Site', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='additional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
