# Generated by Django 5.1.6 on 2025-04-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0013_remove_annotations_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='artifact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additional',
            name='artifactImg',
            field=models.ImageField(blank=True, null=True, upload_to='artifact_image/'),
        ),
    ]
