# Generated by Django 5.1.6 on 2025-04-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0014_additional_artifact_additional_artifactimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additional',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='additional',
            name='artifactImg',
        ),
    ]
