# Generated by Django 5.1.6 on 2025-04-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0015_remove_additional_artifact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='artifacts/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='berry.additional')),
            ],
        ),
    ]
