# Generated by Django 5.1.6 on 2025-04-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0016_artifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='additional',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
