# Generated by Django 5.1.6 on 2025-04-22 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0017_additional_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='siteName',
            field=models.CharField(default='The Berry Site', max_length=255),
        ),
    ]
