# Generated by Django 5.1.6 on 2025-04-22 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0018_artifact_sitename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='page',
        ),
    ]
