# Generated by Django 5.2 on 2025-04-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berry', '0012_stamp'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='berry.stamp')),
            ],
            options={
                'unique_together': {('profile', 'stamp')},
            },
        ),
    ]
